name: referral_client_example
description: Example app demonstrating the referral_client package usage.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  refer_me:
    path: ../
  cupertino_icons: ^1.0.2
  http: ^1.2.2
  device_info_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
